### ISSUE TITLE
Unit tests failed -  Failed to create socket consistently

### ISSUE THREAD

**Issue by TuanHungVU1202** [keva-dev/keva#122]
Building with tests `./gradlew :app:build --parallel` or `./gradlew :app:build` inconsistently cause following errors

```
> Task :core:test
dev.keva.core.server.PersistenceTest save() FAILED (12.1s)

  org.opentest4j.AssertionFailedError
      at dev.keva.core.server.PersistenceTest.sync(PersistenceTest.java:68)
  Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed to create socket.
      at dev.keva.core.server.PersistenceTest.sync(PersistenceTest.java:61)
  Caused by: java.net.ConnectException: Connection refused (Connection refused)
      at dev.keva.core.server.PersistenceTest.sync(PersistenceTest.java:61)

dev.keva.core.server.AOFTest save() FAILED (12.2s)

  org.opentest4j.AssertionFailedError
      at dev.keva.core.server.AOFTest.sync(AOFTest.java:74)
  Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed to create socket.
      at dev.keva.core.server.AOFTest.sync(AOFTest.java:67)
  Caused by: java.net.ConnectException: Connection refused (Connection refused)
      at dev.keva.core.server.AOFTest.sync(AOFTest.java:67)

dev.keva.core.server.PersistenceTest recover() FAILED (1s)

  org.opentest4j.AssertionFailedError
      at dev.keva.core.server.PersistenceTest.recover(PersistenceTest.java:98)
  Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed to create socket.
      at dev.keva.core.server.PersistenceTest.recover(PersistenceTest.java:91)
  Caused by: java.net.ConnectException: Connection refused (Connection refused)
      at dev.keva.core.server.PersistenceTest.recover(PersistenceTest.java:91)

dev.keva.core.server.AOFTest recover() FAILED (1s)

  org.opentest4j.AssertionFailedError
      at dev.keva.core.server.AOFTest.recover(AOFTest.java:106)
  Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed to create socket.
      at dev.keva.core.server.AOFTest.recover(AOFTest.java:99)
  Caused by: java.net.ConnectException: Connection refused (Connection refused)
      at dev.keva.core.server.AOFTest.recover(AOFTest.java:99)

```

**Comment by axblueblader** [comment]
Hey @TuanHungVU1202, thanks for bringing this up
The server start time is definitely inconsistent since it depends on device performance
The 'sleep' was our somewhat lazy way to tackle the problem, increasing 'sleep' time does help but it makes testing much longer, for different machines and especially for the build pipeline too (we're using free stuff with limited time)

I think maybe we can do it differently, change the start function to help with testing by returning a Future or allow user to provide a callback function, what do you think?

**Comment by TuanHungVU1202** [comment]
> Hey @TuanHungVU1202, thanks for bringing this up and making the PR
> 
> The server start time is definitely inconsistent since it depends on device performance
> 
> The 'sleep' was our somewhat lazy way to tackle the problem, increasing 'sleep' time does help but it makes testing much longer, for different machines and especially for the build pipeline too (we're using free stuff with limited time)
> 
> 
> 
> I think maybe we can do it differently, change the start function to help with testing by returning a Future or allow user to provide a callback function, what do you think?
> 
> 

Make sense for me, I didn't think about the limitation from Github Actions?. It was quite annoying the build keep failing.
I'll try with the suggested approach.

**Comment by tuhuynh27** [comment]
@TuanHungVU1202 @axblueblader We can utilize `CompletableFuture`:

```java
CompletableFuture<Void> future = server.start();
// Wait until the server is ready.
future.join();
```

**Comment by tuhuynh27** [comment]
@TuanHungVU1202 @axblueblader We can consider updating these code:
https://github.com/keva-dev/keva/blob/develop/core/src/main/java/dev/keva/core/server/KevaServer.java#L103-L119

From `void` method

```java
@Override
public void run() {
```

to return a `CompletableFuture`:

```java
@Override
public CompletableFuture<Void> run() {
```

```java
// Init CompletableFuture object
CompletableFuture<Void> future = new CompletableFuture<>();
ChannelFuture sync = server.bind(config.getPort()).sync();
log.info("Ready to accept connections");
// Server is ready at this line, so release the future
future.complete(null);

// ... if crash or cannot start 
```java
catch (Exception e) {
    log.error("Failed to start server: ", e);
    // Release err future
    future.completeExceptionally(e);
}
```

Usage:

```java
CompletableFuture<Void> future = server.run();
// Wait until the server is ready.
future.join();
```
