### ISSUE TITLE
Handle null exception when AOF file is empty

### ISSUE THREAD

**Issue by tuhuynh27** [keva-dev/keva#96]
Currently, if we run Keva AOF mode, no command, and then restart, this error happens:

```
01:54:57.848 [main] ERROR dev.keva.core.aof.AOFContainer - Error while reading AOF command
java.io.EOFException: null
        at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3078)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1618)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
        at dev.keva.core.aof.AOFContainer.read(AOFContainer.java:114)
        at dev.keva.core.aof.AOFManager.init(AOFManager.java:35)
        at dev.keva.core.server.KevaServer.run(KevaServer.java:103)
        at dev.keva.app.Application.main(Application.java:27)
```

**Comment by the123saurav** [comment]
Isnt that expected behaviour as there is nothing to read and we have reached EOF?

**Comment by the123saurav** [comment]
Maybe we should just not log that exception

**Comment by tuhuynh27** [comment]
Yes @the123saurav

**Comment by the123saurav** [comment]
Alright will just remove that log line
